### PR TITLE
Milestone 1 - Responsive webpage using bootstrap framework

### PR DESCRIPTION
**Pull request by alishabab**
## In this milestone I :
- Used bootstrap for responsive design
- Used bootstrap grid system for layout
- Added a responsive fixed navigation bar
- Minimal use of custom css classes
- Fontawesome library for icons
- Google font API for fonts
- Masonry layout

### CODE REVIEW

**Comment by mikenath223** [comment]
**Pull request currently under review by Michgolden Ukeje (TSE).**
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Great JOB 👏👏👏

**You did really good @alishabab 👌**
Your project looks quite responsive.

**STATUS: ⭕ CHANGES REQUIRED**

There remain just a few issues to fix before proceeding👇:

- [x] Required - The subscribe section that comes before the footer looks different from the original webpage.

**THIS IS YOURS👇**
ice_screenshot_20200326-101320


**THIS IS THE WAY IT'S SUPPOSED TO LOOK👇**
ice_screenshot_20200326-101345

Kindly make changes to yours.

- [x] Also add a menu icon on **all breakpoints** just as it looks on the original webpage.[Screenshot]👇
ice_screenshot_20200326-101447

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by alishabab** [comment]
Thank you @mikenath223 , done the required changes

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS @alishabab  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

However, kindly fix this issue before merging👇:

- [x] Remove all comment in your HTML and CSS files. Read this article on CSS bad practices to avoid  [article](https://speckyboy.com/good-bad-css-practices)) and go through this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright.

Kindly fix these issues and don't forget to fill the project completion form
Good luck with the next project.👍

HAPPY CODING👨‍💻

**Comment by alishabab** [comment]
Merged.

**Pull request merged**
